FROM golang:alpine as builder
RUN apk --no-cache add git

WORKDIR /app/consignment-service

COPY . .

RUN go mod download

RUN CGO_ENABLE=0 GOOS=linux go build -a -installsuffix cgo -o consignment-service


#######
FROM alpine:latest
RUN apk --no-cache add ca-certificates

RUN mkdir /app
WORKDIR /app
# ADD consignment-service /app/consignment-service

COPY --from=builder /app/consignment-service .


CMD ["./consignment-service"]